from contadorCompartido import ContadorCompartido


c1=ContadorCompartido()
c2=ContadorCompartido()
c3=ContadorCompartido()
c4=ContadorCompartido()
c5=ContadorCompartido()
c6=ContadorCompartido()
c7=ContadorCompartido()
c8=ContadorCompartido()
c9=ContadorCompartido()
c10=ContadorCompartido()

c1.start()
c2.start()
c3.start()
c4.start()
c5.start()
c6.start()
c7.start()
c8.start()
c9.start()
c10.start()


#c1.run()
#c2.run()
#c3.run()
#c4.run()
#c5.run()
#c6.run()
#c7.run()
#c8.run()
#c9.run()
#c10.run()